export const resourceNames = {
  ebs_volume: "EBS Volume",
  ec2_instance: "EC2 Instance",
  vpc: "VPC",
  subnet: "Subnet",
  security_group: "Security Group",
  sns_topic: "SNS Topic",
  sqs_queue: "SQS Queue",
  dynamodb_table: "DynamoDB Table",
  cloudsql_instance: "Cloud SQL Instance",
  compute_instance: "Compute Instance",
  vpc_network: "VPC Network",
  subnetwork: "Subnetwork",
  firewall_rule: "Firewall Rule",
  pubsub_topic: "Pub/Sub Topic",
  pubsub_subscription: "Pub/Sub Subscription",
  service_account: "Service Account",
  project_iam_policy: "IAM Policy",
};
export const typeName = (value) => resourceNames[value] || value;
